name: bet_predictions
description: Betting predictions app
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  google_mobile_ads: ^7.0.0   # adaugă aceasta
  
dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"  # icon-ul tău
  
flutter:
  uses-material-design: true